# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alma Bocaj
email: alma@almabocaj.com
description: > # this means to ignore newlines until "baseurl:"
  International Law, European Law & Political Sciences
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.almabocaj.com" # the base hostname & protocol for your site
permalink: "/:year/:month/:title"
twitter_username: jekyllrb
github_username:  jekyll
gems:
  - jekyll-redirect-from

category_dir: "category"
category_title_prefix: ""

# Build settings
markdown: kramdown
